Class {
	#name : #GdxVisitor,
	#superclass : #Object,
	#category : #'Gdx-Model'
}

{ #category : #visiting }
GdxVisitor >> visitAref: aGdxArrayedStructureReference [
	self shouldBeImplemented
]

{ #category : #visiting }
GdxVisitor >> visitBoundary: aGdxBoundary [
	self shouldBeImplemented
]

{ #category : #visiting }
GdxVisitor >> visitBoxText: aGdxBoxText [
	self shouldBeImplemented
]

{ #category : #visiting }
GdxVisitor >> visitLibrary: aGdxLibrary [
	self shouldBeImplemented
]

{ #category : #visiting }
GdxVisitor >> visitPath: aGdxPath [
	self shouldBeImplemented
]

{ #category : #visiting }
GdxVisitor >> visitSref: aGdxStructureReference [
	self shouldBeImplemented
]

{ #category : #visiting }
GdxVisitor >> visitStructure: aGdxStructure [
	self shouldBeImplemented
]
