Class {
	#name : #DxfVersion,
	#superclass : #Object,
	#category : #'KFDxf-Model'
}

{ #category : #'as yet unclassified' }
DxfVersion class >> specJson [
	"(NeoJSONReader fromString: self specJson) explore."
	"(NeoJSONWriter toStringPretty: (NeoJSONReader fromString: self specJson)) explore."
	^'{
	"AC1006": { "codeInJapanese": "Shift_JIS", "ReleaseStrings": ["GX-III"] },
	"AC1009": { "codeInJapanese": "Shift_JIS", "ReleaseStrings": ["GX-5", "Release12J"]  },
	"AC1012": { "codeInJapanese": "Shift_JIS", "ReleaseStrings": ["Release13J"]  },
	"AC1014": { "codeInJapanese": "Shift_JIS", "ReleaseStrings": ["Release14"]  },
	"AC1015": { "codeInJapanese": "Shift_JIS", "ReleaseStrings": ["2000", "2000i", "2002"]  },
	"AC1018": { "codeInJapanese": "Shift_JIS", "ReleaseStrings": ["2004", "2005", "2006"]  },
	"AC1021": { "codeInJapanese": "Shift_JIS", "ReleaseStrings": ["2007", "2008", "2009"]  },
	"AC1024": { "codeInJapanese": "Shift_JIS", "ReleaseStrings": ["2010", "2011", "2012"]  },
	"AC1027": { "codeInJapanese": "Shift_JIS", "ReleaseStrings": ["2013", "2014"]  }
}'
]
